export const states = [
  '-- No Answer --',
  'Alaska',
  'Alabama',
  'Arkansas',
  'American Samoa',
  'Arizona',
  'California',
  'Colorado',
  'Connecticut',
  'District of Columbia',
  'Delaware',
  'Florida',
  'Georgia',
  'Guam',
  'Hawaii',
  'Iowa',
  'Idaho',
  'Illinois',
  'Indiana',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Massachusetts',
  'Maryland',
  'Maine',
  'Michigan',
  'Minnesota',
  'Missouri',
  'Mississippi',
  'Montana',
  'North Carolina',
  'North Dakota',
  'Nebraska',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'Nevada',
  'New York',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Puerto Rico',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Virginia',
  'Virgin Islands',
  'Vermont',
  'Washington',
  'Wisconsin',
  'West Virginia',
  'Wyoming'
];

export const yesNoArray = ['Yes', 'No', 'Unknown'];

export const REPORTS_NAME = {
  "contact-report" :"Contact Report",
  "student-info-report" :"Student Info Report",
  "note-report" :"Note Report",
  "referred-report" :"Referred Report",
  "user-permission-report" :"User Permission Report",
  "gc-navigator-points-report" :"GC Navigator Points Report",
  "gc-navigator-redemption-report" :"GC Navigator Redemption Report",
  "gc-navigator-report" :"GC Navigator Report",
  "case-management-report" :"Case Management Report",
  "academic-progress-report" :"Academic Progress Report",
  "engagement-report" :"Engagement Report",
};

export const appointments = [
  { value: null, text: 'Select Time' },
  { value: "08:00", text: '08:00AM' },
  { value: "08:15", text: '08:15AM' },
  { value: "08:30", text: '08:30AM' },
  { value: "08:45", text: '08:45AM' },
  { value: "09:00", text: '09:00AM' },
  { value: "09:15", text: '09:15AM' },
  { value: "09:30", text: '09:30AM' },
  { value: "09:45", text: '09:45AM' },
  { value: "10:00", text: '10:00AM' },
  { value: "10:15", text: '10:15AM' },
  { value: "10:30", text: '10:30AM' },
  { value: "10:45", text: '10:45AM' },
  { value: "11:00", text: '11:00AM' },
  { value: "11:15", text: '11:15AM' },
  { value: "11:30", text: '11:30AM' },
  { value: "11:45", text: '11:45AM' },
  { value: "12:00", text: '12:00PM' },
  { value: "12:15", text: '12:15PM' },
  { value: "12:30", text: '12:30PM' },
  { value: "12:45", text: '12:45PM' },
  { value: "13:00", text: '01:00PM' },
  { value: "13:15", text: '01:15PM' },
  { value: "13:30", text: '01:30PM' },
  { value: "13:45", text: '01:45PM' },
  { value: "14:00", text: '02:00PM' },
  { value: "14:15", text: '02:15PM' },
  { value: "14:30", text: '02:30PM' },
  { value: "14:45", text: '02:45PM' },
  { value: "15:00", text: '03:00PM' },
  { value: "15:15", text: '03:15PM' },
  { value: "15:30", text: '03:30PM' },
  { value: "15:45", text: '03:45PM' },
  { value: "16:00", text: '04:00PM' }
];
